version: '3'
services:

  app:
    build: .
    image: covid-seg
    command: python preprocess.py #run_inference.py 
    environment:
     - PATIENT_FOLDER=./patients
     - IMAGE_FOLDER=./images
    volumes:
     - ./model/:/app/model
     - ./images:/app/images
     - ./patients:/app/patients
     - ./output:/app/output
    networks:
     - backend
    deploy:
     resources:
       limits:
         cpus: '0.001'
         memory: 8GB
networks:
  backend:
